version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: kenty
      POSTGRES_PASSWORD: kenty
      POSTGRES_DB: kenty
    restart: always
    networks:
      - network
networks:
  network:
    driver: bridge